### ISSUE TITLE
README.md:6: create an issue for the first time using pdd

### ISSUE THREAD

**Issue by 0pdd** [raboley/the-heroes-journey#2]
The puzzle `2-45396494` from #2 has to be resolved: 

https://github.com/raboley/the-heroes-journey/blob/04d4644c2e752dae589e4073b837be46bf12166b/README.md#L6-L6

The puzzle was created by @raboley on 05-Jul-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#2](https://github.com/raboley/the-heroes-journey/issues/2) is still not solved.

**Comment by raboley** [comment]
this was closed
