### ISSUE TITLE
Make a GitHub action for pdd

### ISSUE THREAD

**Issue by raboley** [raboley/the-heroes-journey#7]
I want to run the pdd stuff server side on commit so it won't make commit take as long.

**Comment by 0pdd** [comment]
@raboley the puzzle [#8](https://github.com/raboley/the-heroes-journey/issues/8) is still not solved.

**Comment by 0pdd** [comment]
@raboley the only puzzle [#8](https://github.com/raboley/the-heroes-journey/issues/8) is solved here.

**Comment by raboley** [comment]
GitHub action created really easily actually.
