### ISSUE TITLE
Script Examples in Documentation using Embedme

### ISSUE THREAD

**Issue by raboley** [raboley/the-heroes-journey#9]

**Comment by 0pdd** [comment]
@raboley the puzzle [#15](https://github.com/raboley/the-heroes-journey/issues/15) is still not solved.

**Comment by 0pdd** [comment]
@raboley the only puzzle [#15](https://github.com/raboley/the-heroes-journey/issues/15) is solved here.

**Comment by raboley** [comment]
added documentation
